// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NEGOTIATION_CONTROLMESSAGES_H_
#define FLATBUFFERS_GENERATED_NEGOTIATION_CONTROLMESSAGES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ControlMessages {

struct ClientId;
struct ClientIdBuilder;
struct ClientIdT;

inline const ::flatbuffers::TypeTable *ClientIdTypeTable();

struct ClientIdT : public ::flatbuffers::NativeTable {
  typedef ClientId TableType;
  int64_t id = 0;
};

struct ClientId FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientIdT NativeTableType;
  typedef ClientIdBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ClientIdTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  int64_t id() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID, 8) &&
           verifier.EndTable();
  }
  ClientIdT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientIdT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientId> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientIdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientIdBuilder {
  typedef ClientId Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int64_t id) {
    fbb_.AddElement<int64_t>(ClientId::VT_ID, id, 0);
  }
  explicit ClientIdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientId> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientId>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientId> CreateClientId(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t id = 0) {
  ClientIdBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientId> CreateClientId(::flatbuffers::FlatBufferBuilder &_fbb, const ClientIdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ClientIdT *ClientId::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientIdT>(new ClientIdT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientId::UnPackTo(ClientIdT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); _o->id = _e; }
}

inline ::flatbuffers::Offset<ClientId> CreateClientId(::flatbuffers::FlatBufferBuilder &_fbb, const ClientIdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientId::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientId> ClientId::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientIdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientIdT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _o->id;
  return ControlMessages::CreateClientId(
      _fbb,
      _id);
}

inline const ::flatbuffers::TypeTable *ClientIdTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_LONG, 0, -1 }
  };
  static const char * const names[] = {
    "id"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace ControlMessages

#endif  // FLATBUFFERS_GENERATED_NEGOTIATION_CONTROLMESSAGES_H_
